### ISSUE TITLE
Slight layout issue in Safari

### ISSUE THREAD

**Issue by benmatselby** [GoogleChromeLabs/web-a-skeb#15]
Hi there @rowan-m 

Love this by the way.. 

On Safari, be it the desktop or iPhone version, the main window we get to play in is squashed

![screenshot 2019-01-09 at 15 54 29](https://user-images.githubusercontent.com/178634/50910917-afaa5800-1426-11e9-8b76-7526b7aa63b0.png)

**Comment by benmatselby** [comment]
Looks fine on Desktop, just a minor formatting issue on the iPhone in Portrait mode.. Landscape mode on the iPhone is now fine :D

![img_6d9e7b40b91e-1](https://user-images.githubusercontent.com/178634/50912702-b20eb100-142a-11e9-81cb-6d2bae6f12cb.jpeg)

**Comment by rowan-m** [comment]
Need to grab an iphone for some testing here, but it looks like the issue might be: https://www.eventbrite.com/engineering/mobile-safari-why/
Need to experiment with adding:
```css
html,
body {
  /* Allows content to fill the viewport and go beyond the bottom */
  height: 100%;
  /* Allows you to scroll below the viewport; default value is visible */
  overflow-y: scroll;
  /* To smooth any scrolling behavior */
  -webkit-overflow-scrolling: touch;
}
```
